USE Poc;
CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, name VARCHAR(11), age INT);
SHOW CREATE TABLE ${TABLE_NAME};
INSERT INTO ${TABLE_NAME} VALUES (1 ,'Green', 18), (2, 'Jim', 24);
SELECT * FROM ${TABLE_NAME};