CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT);
INSERT INTO ${TABLE_NAME} VALUE (1,123),(2,456);
CREATE VIEW ${TABLE_NAME}_v AS SELECT * FROM ${TABLE_NAME} WHERE id = 1;
SELECT * FROM ${TABLE_NAME}_v;
CREATE OR REPLACE VIEW ${TABLE_NAME}_v AS SELECT * FROM ${TABLE_NAME} WHERE id = 2;
SELECT * FROM ${TABLE_NAME}_v;
DROP VIEW ${TABLE_NAME}_v;