SELECT ASCII('abc');
SELECT CHAR(97);
SELECT CHAR_LENGTH('abc');
SELECT CONCAT('AB', 'C');
SELECT INSERT('abcd12345', 5, 5, 'ABCDE');
SELECT LCASE('ABC');
SELECT LEFT('ABC', 2);
SELECT LOCATE('CD', 'ABCDE');
SELECT LOWER('ABC');
SELECT LPAD('ABC', 5, '??');
SELECT LTRIM('  ABC');
SELECT OCTET_LENGTH('ABCD');
SELECT POSITION('CD' IN 'ABCDE');
SELECT REPLACE('123123123', '123', 'ABC');
SELECT RIGHT('123456', 3);
SELECT RPAD('ABC', 5, '??');
SELECT RTRIM('ABC   ');
SELECT CONCAT('A', SPACE(3));
SELECT SUBSTRING('ABCD123456', 5);
SELECT SUBSTR('ABCD123456', 5);
SELECT TRIM('  ABC  ');
SELECT UCASE('abc');
SELECT UPPER('abc-def');
SELECT INSTR('ABCD', 'C');
SELECT UNHEX('414243');


