CREATE TABLE ${TABLE_NAME}(id INT PRIMARY KEY, name VARCHAR(11), age INT, salary DECIMAL(10, 2));
INSERT INTO ${TABLE_NAME} VALUES (1, 'Alice', 25, 5000.00), (2, 'Bob', 30, 6000.00), (3, 'Charlie', 35, 7000.00);
SELECT COUNT(*) FROM ${TABLE_NAME};
SELECT LENGTH(name), UPPER(name), LOWER(name) FROM ${TABLE_NAME};
SELECT ROUND(salary), FLOOR(salary), CEILING(salary) FROM ${TABLE_NAME};
SELECT VERSION();
SELECT CURRENT_DATE(), CURRENT_TIME(), NOW();
SELECT DATE_ADD('2020-01-01', INTERVAL 1 MONTH) 1_MONTH_LATER, DATE_SUB('2020-01-01',INTERVAL 1 MONTH) 1_MONTH_BEFORE;

