CREATE TABLE ${TABLE_NAME} (c1 VARCHAR(10), c2 VARCHAR(10), INDEX ((LOWER(c1))));
INSERT INTO ${TABLE_NAME} VALUE ('a','b'),('c','d');
ANALYZE TABLE ${TABLE_NAME};
EXPLAIN SELECT LOWER(c1) FROM ${TABLE_NAME} where LOWER(c1) = 'a';