CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY , t TIMESTAMP);
INSERT INTO ${TABLE_NAME} VALUE (1, NOW());
SELECT * FROM ${TABLE_NAME};
SET time_zone = 'Europe/Helsinki';
SELECT * FROM ${TABLE_NAME};
