USE poc;
CREATE TABLE ${TABLE_NAME}(id INT PRIMARY KEY)
    PARTITION BY RANGE (id)(
        PARTITION p0 VALUES LESS THAN (5),
        PARTITION p1 VALUES LESS THAN (10));
INSERT INTO ${TABLE_NAME} VALUES (1),(2),(3),(9);
SELECT * FROM ${TABLE_NAME} PARTITION (p0);
EXPLAIN SELECT * FROM ${TABLE_NAME} WHERE id = 9;

