CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, name VARCHAR(11));
INSERT INTO ${TABLE_NAME} VALUES (1, 'Jim'), (2, 'Green'), (3, NULL);
SELECT * FROM ${TABLE_NAME} WHERE name IS NULL;
SELECT * FROM ${TABLE_NAME} WHERE name IS NOT NULL;