CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT, c2 INT, INDEX k(c1));
INSERT INTO ${TABLE_NAME} VALUES (1, 100, 200);
ANALYZE TABLE ${TABLE_NAME};
EXPLAIN SELECT * FROM ${TABLE_NAME} WHERE id = 1;
CREATE BINDING FOR
    SELECT * FROM ${TABLE_NAME} WHERE id = 1
    USING
    SELECT * FROM ${TABLE_NAME} USE INDEX(k) WHERE id = 1;
EXPLAIN SELECT * FROM ${TABLE_NAME} WHERE id = 1;
SHOW BINDINGS;
DROP BINDING FOR SELECT * FROM ${TABLE_NAME} WHERE id = 1;
SHOW BINDINGS;
