CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY)
    PARTITION BY HASH (id) PARTITIONS 4;
INSERT INTO ${TABLE_NAME} VALUES (1),(2),(3),(4),(5),(6);
EXPLAIN SELECT * FROM ${TABLE_NAME} WHERE id IN (1,3,5);
