CREATE TABLE ${TABLE_NAME} (id INT, name VARCHAR(11), age INT);
ALTER TABLE ${TABLE_NAME} ADD UNIQUE INDEX k(age);
INSERT INTO ${TABLE_NAME} VALUES (1, 'Jim', 18);
DROP INDEX k ON ${TABLE_NAME};
INSERT INTO ${TABLE_NAME} VALUES (1, 'Green', 18);