USE poc;
CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, name VARCHAR(11), age INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 'Jim', 18),(2, 'Green', 24);
BEGIN;
UPDATE ${TABLE_NAME} SET age = 24 WHERE id = 1;
SELECT SLEEP(5);
UPDATE ${TABLE_NAME} SET age = 18 WHERE id = 2;
## -
SELECT SLEEP(2);
USE poc;
BEGIN;
UPDATE ${TABLE_NAME} SET age = 18 WHERE id = 2;
UPDATE ${TABLE_NAME} SET age = 24 WHERE id = 1;