CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, name VARCHAR(11));
SELECT SLEEP(1);
INSERT INTO ${TABLE_NAME} VALUES (1, 'Jim');
SELECT SLEEP(1);
UPDATE ${TABLE_NAME} SET name = 'Green' WHERE id = 1;
SELECT * FROM ${TABLE_NAME} WHERE id = 1;
SELECT * FROM ${TABLE_NAME} AS OF TIMESTAMP (SELECT DATE_SUB(NOW(), INTERVAL 0.1 SECOND));