CREATE TABLE ${TABLE_NAME} (id INT);
BEGIN;
INSERT INTO ${TABLE_NAME} VALUES (1);
SAVEPOINT sp;
INSERT INTO ${TABLE_NAME} VALUES (2);
SELECT * FROM ${TABLE_NAME};
ROLLBACK TO sp;
SELECT * FROM ${TABLE_NAME};