CREATE TABLE ${TABLE_NAME}(col1 MEDIUMINT, col2 BIGINT NOT NULL, PRIMARY KEY(col1, col2));
INSERT INTO ${TABLE_NAME} VALUES (1,10), (0,8), (-1,9), (13,12), (3,4), (1,17), (2,-2), (2,6), (11,23) ;
SELECT COUNT(*) FROM ${TABLE_NAME};
SELECT AVG(col1 + col2) FROM ${TABLE_NAME};
SELECT DISTINCT(col1) FROM ${TABLE_NAME};
SELECT MAX(col1), MIN(col1) FROM ${TABLE_NAME};
SELECT SUM(col1),SUM(col2),SUM(col1 + col2) FROM ${TABLE_NAME};
SELECT GROUP_CONCAT(col1) FROM ${TABLE_NAME} GROUP BY col1;

