CREATE TABLE ${TABLE_NAME}(col1 MEDIUMINT KEY, col2 BIGINT);
INSERT INTO ${TABLE_NAME} VALUES (1,10),(0,8),(-1,NULL),(16,12),(3,4),(11,NULL),(2,-2),(12,NULL),(13,23);
SELECT COALESCE(NULL, NULL, 1, 2) FROM DUAL;
SELECT COALESCE(NULL, NULL, NULL, NULL) FROM DUAL;
SELECT * FROM ${TABLE_NAME} WHERE ISNULL(col2);
SELECT NULLIF(1,1) FROM DUAL;
SELECT NULLIF(2,3) FROM DUAL;
SELECT IFNULL(NULL, 'ABC') FROM DUAL;
SELECT IFNULL('1', 'ABC') FROM DUAL;