CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT);
ALTER TABLE ${TABLE_NAME} ADD UNIQUE KEY k(`c1`);
INSERT INTO ${TABLE_NAME} VALUE (1, 100), (2, 200), (3, 300);
ANALYZE TABLE ${TABLE_NAME};
EXPLAIN SELECT * FROM ${TABLE_NAME} WHERE c1 > 1;
INSERT INTO ${TABLE_NAME} VALUE (4, 300);

