CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT, c2 INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 10, 100), (2, 20, 200);
ALTER TABLE ${TABLE_NAME} ADD INDEX k1(c1);
ALTER TABLE ${TABLE_NAME} ADD INDEX k2(c2);
SHOW CREATE TABLE ${TABLE_NAME};