CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT, c2 INT);
ALTER TABLE ${TABLE_NAME} ADD INDEX k(c1);
INSERT INTO ${TABLE_NAME} VALUE (1, 10, 100),(2, 20, 200);
ANALYZE TABLE ${TABLE_NAME} ;
EXPLAIN SELECT /*+ USE_INDEX(${TABLE_NAME} , k) */ c1, c2 FROM ${TABLE_NAME}  WHERE c1 = 10;