USE poc;
CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY);
INSERT INTO ${TABLE_NAME} VALUES (1),(2),(3);
EXPLAIN ANALYZE SELECT * FROM ${TABLE_NAME} WHERE id IN (1, 2, 3);
ALTER TABLE ${TABLE_NAME} CACHE;
SELECT * FROM ${TABLE_NAME};
EXPLAIN ANALYZE SELECT * FROM ${TABLE_NAME} WHERE id IN (1, 2, 3);
TRACE FORMAT='row' SELECT * FROM ${TABLE_NAME};
