CREATE GLOBAL TEMPORARY TABLE ${TABLE_NAME} (id INT PRIMARY KEY) ON COMMIT DELETE ROWS;
BEGIN;
INSERT INTO ${TABLE_NAME} VALUE (1),(2),(3);
SELECT * FROM ${TABLE_NAME};
COMMIT;
SELECT NOW();
SELECT * FROM ${TABLE_NAME};
SELECT SLEEP(7);
## -
SELECT SLEEP(5);
SELECT NOW();
SELECT * FROM ${TABLE_NAME};

