CREATE TEMPORARY TABLE ${TABLE_NAME} (id INT PRIMARY KEY );
INSERT INTO ${TABLE_NAME} VALUE (1), (2), (3);
SELECT NOW();
SELECT * FROM ${TABLE_NAME};
## -
CREATE TEMPORARY TABLE ${TABLE_NAME} (id INT PRIMARY KEY );
INSERT INTO ${TABLE_NAME} VALUE (4), (5), (6);
SELECT NOW();
SELECT * FROM ${TABLE_NAME};
## -
SELECT SLEEP(5);
SELECT NOW();
SELECT * FROM ${TABLE_NAME};