set sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY , name VARCHAR(11), age INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 'Jim', 18), (2, 'Green', 18), (3, 'Tom', 24), (4, 'Lucy', 8);
SELECT * FROM ${TABLE_NAME} GROUP BY age;