CREATE TABLE ${TABLE_NAME} (id INT, name VARCHAR(11), age INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 'Green', 18), (2, 'Lucy', 14), (3, 'Jim', 24);
DELETE FROM ${TABLE_NAME} WHERE id = 1;
SELECT * FROM ${TABLE_NAME};