CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY , c1 INT, c2 INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 10, 100), (2, 20, 200), (3, 30, 300);
SELECT * FROM ${TABLE_NAME} WHERE id > 2 AND id <= 3;
SELECT * FROM ${TABLE_NAME} WHERE id IN (2, 3);
SELECT * FROM ${TABLE_NAME} WHERE id BETWEEN 1 AND 2;