CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY , c1 VARCHAR(11));
INSERT INTO ${TABLE_NAME} VALUE (1,'a'),(2,'b'),(3,'comp');
CREATE TABLE ${TABLE_NAME}_bak LIKE ${TABLE_NAME};
INSERT INTO ${TABLE_NAME}_bak SELECT * FROM ${TABLE_NAME};
SELECT * FROM ${TABLE_NAME}_bak;