CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 10), (2, 20);
CREATE TABLE ${TABLE_NAME}_MERGE LIKE ${TABLE_NAME};
INSERT INTO ${TABLE_NAME}_MERGE VALUES (1, 100);
INSERT INTO ${TABLE_NAME}_MERGE SELECT * FROM ${TABLE_NAME} ON DUPLICATE KEY UPDATE c1 = '10';
SELECT * FROM ${TABLE_NAME}_MERGE;
