CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 100), (2, 200), (3, 300);
SELECT * FROM ${TABLE_NAME} ORDER BY id;
SELECT * FROM ${TABLE_NAME} ORDER BY id LIMIT 2;