CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY ,c1 INT, c2 INT);
INSERT INTO ${TABLE_NAME} VALUES (1,10,100),(2,20,200),(3,30,300);
WITH CTE_TEST AS
         (SELECT * FROM ${TABLE_NAME})
SELECT * FROM CTE_TEST a, CTE_TEST b WHERE a.id = b.id ORDER BY a.id DESC;