CREATE TABLE ${TABLE_NAME} (id INT, name VARCHAR(11), age INT);
SHOW CREATE TABLE ${TABLE_NAME};
INSERT INTO ${TABLE_NAME} VALUES (1, 'Green', 18), (2, 'Jim', 24), (3, '小红', 12);
SELECT * FROM ${TABLE_NAME};