CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY , c1 VARCHAR(11), c2 VARCHAR(11)) CHARACTER SET gbk;
SHOW CREATE TABLE ${TABLE_NAME};
INSERT INTO ${TABLE_NAME} VALUES (1, '中国', 'gbk');
SELECT * FROM ${TABLE_NAME};
