CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, name VARCHAR(50), age INT) CHARACTER SET gbk;
SHOW CREATE TABLE ${TABLE_NAME};
INSERT INTO ${TABLE_NAME} VALUES (1, '小明', 18), (2, '小红', 19);
SELECT * FROM ${TABLE_NAME};
