CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, num1 INT, num2 INT, str1 VARCHAR(50), str2 VARCHAR(50));
INSERT INTO ${TABLE_NAME} VALUES (1, 10, 5, 'abc', 'def'), (2, 20, 3, 'xyz', 'xyz'), (3, 15, 8, 'pqr', 'pqq');
SELECT * FROM ${TABLE_NAME} WHERE num1 = 20;
SELECT * FROM ${TABLE_NAME} WHERE num2 <> 5;
SELECT * FROM ${TABLE_NAME} WHERE num1 > 15;
SELECT * FROM ${TABLE_NAME} WHERE num2 < 5;
SELECT * FROM ${TABLE_NAME} WHERE num1 >= 10;
SELECT * FROM ${TABLE_NAME} WHERE num2 <= 3;
SELECT * FROM ${TABLE_NAME} WHERE str1 = str2;
