CREATE TABLE ${TABLE_NAME}(id INT PRIMARY KEY, num1 INT, num2 INT, flag1 BOOLEAN, flag2 BOOLEAN);
INSERT INTO ${TABLE_NAME} VALUES (1, 10, 5, TRUE, FALSE), (2, 20, 3, TRUE, TRUE), (3, 15, 8, FALSE, FALSE);
SELECT * FROM ${TABLE_NAME} WHERE flag1 AND flag2;
SELECT * FROM ${TABLE_NAME} WHERE flag1 OR flag2;
SELECT id, num1, num2, flag1, flag2, NOT flag1 AS not_flag1, NOT flag2 AS not_flag2 FROM ${TABLE_NAME};
