CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT, c2 INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 10, 100), (2, 20 , 200);
SELECT * FROM ${TABLE_NAME} WHERE  c1 > 10;
SELECT * FROM ${TABLE_NAME} WHERE c2 < 200;
SELECT * FROM ${TABLE_NAME} WHERE id = 1;
SELECT * FROM ${TABLE_NAME} WHERE id <> 1;