CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT, c2 INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 100, 200);
EXPLAIN SELECT * FROM ${TABLE_NAME};
ANALYZE TABLE ${TABLE_NAME};
EXPLAIN SELECT * FROM ${TABLE_NAME};