CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT);
ALTER TABLE ${TABLE_NAME} ADD INDEX k (c1);
INSERT INTO ${TABLE_NAME} VALUE (1, 10), (2, 20);
ANALYZE TABLE ${TABLE_NAME};
EXPLAIN SELECT c1 FROM ${TABLE_NAME} WHERE c1 = 1;
EXPLAIN SELECT /*+ IGNORE_INDEX(${TABLE_NAME}, k) */ c1 FROM ${TABLE_NAME} WHERE c1 = 1;