CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY);
INSERT INTO ${TABLE_NAME} VALUES (1), (2), (3);
ANALYZE TABLE ${TABLE_NAME};
EXPLAIN SELECT /*+ HASH_AGG() */ COUNT(*) FROM ${TABLE_NAME};
EXPLAIN SELECT /*+ STREAM_AGG() */ COUNT(*) FROM ${TABLE_NAME};
