CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT, c2 INT);
EXPLAIN INSERT INTO ${TABLE_NAME} VALUES (1, 100, 1000);
INSERT INTO ${TABLE_NAME} VALUES (1, 100, 1000);
EXPLAIN SELECT * FROM ${TABLE_NAME} WHERE id = 1;
EXPLAIN UPDATE ${TABLE_NAME} SET c1 = 200, c2 = 2000 WHERE id = 1;
EXPLAIN DELETE FROM ${TABLE_NAME} WHERE id = 1;