SET GLOBAL tidb_enable_check_constraint = ON;
CREATE TABLE ${TABLE_NAME}(a INT CHECK(a > 10) NOT ENFORCED, b INT, c INT, CONSTRAINT c1 CHECK (b > c));
ALTER TABLE ${TABLE_NAME} ADD CONSTRAINT CHECK (1 < c);
SHOW CREATE TABLE ${TABLE_NAME};
INSERT INTO ${TABLE_NAME} VALUES (1, 10, 100);
SET GLOBAL tidb_enable_check_constraint = OFF;