CREATE TABLE ${TABLE_NAME}(id INT PRIMARY KEY, name VARCHAR(11),age INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 'Jim', 18);
INSERT INTO ${TABLE_NAME} VALUES (1, 'Green', 24);
INSERT INTO ${TABLE_NAME} VALUES (NULL, 'Green', 24);