CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, name VARCHAR(11), CONSTRAINT min_username_length CHECK (CHARACTER_LENGTH(name) >=4));
INSERT INTO ${TABLE_NAME} VALUES (1, 'Jim');
INSERT INTO ${TABLE_NAME} VALUES (2, 'Green');