CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 VARCHAR(11));
INSERT INTO ${TABLE_NAME} VALUE (1, 'ABC');
BEGIN;
SELECT * FROM ${TABLE_NAME} WHERE id = 1;
SELECT SLEEP(5);
SELECT NOW();
SELECT * FROM ${TABLE_NAME} WHERE id = 1;
COMMIT;
SELECT * FROM ${TABLE_NAME} WHERE id = 1;
## -
USE poc;
SELECT SLEEP(2);
SELECT NOW();
UPDATE ${TABLE_NAME} SET c1 = 'ABCDEFG' WHERE id = 1;