SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 VARCHAR(11));
INSERT INTO ${TABLE_NAME} VALUE (1, 'hello!');
BEGIN;
SELECT NOW();
SELECT * FROM ${TABLE_NAME} WHERE id = 1;
SELECT SLEEP(5);
SELECT NOW();
SELECT * FROM ${TABLE_NAME} WHERE id = 1;
## -
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT SLEEP(2);
SELECT NOW();
UPDATE ${TABLE_NAME} SET c1 = 'TiDB!' WHERE id = 1;