CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 100), (2, 200);
SELECT NOW();
LOCK TABLES ${TABLE_NAME} WRITE;
SELECT SLEEP(5);
SELECT NOW();
UNLOCK TABLES;
## -
SELECT SLEEP(3);
SELECT NOW();
INSERT INTO ${TABLE_NAME} VALUES (3, 300);
SELECT SLEEP(5);
SELECT NOW();
INSERT INTO ${TABLE_NAME} VALUES (3, 300);