CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT);
INSERT INTO ${TABLE_NAME} VALUES (1, 100);
BEGIN;
SELECT NOW();
SELECT * FROM ${TABLE_NAME} FOR UPDATE;
SELECT SLEEP(10);
SELECT NOW();
COMMIT;
## -
SELECT SLEEP(3);
SELECT NOW();
UPDATE ${TABLE_NAME} SET c1 = 1000 WHERE id = 1;