CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT);
INSERT INTO ${TABLE_NAME} VALUE (1,123456789);
BEGIN OPTIMISTIC;
SELECT NOW();
UPDATE ${TABLE_NAME} SET c1 = 123 WHERE id = 1;
SELECT SLEEP(5);
COMMIT;
## -
USE Poc;
SELECT SLEEP(2);
BEGIN OPTIMISTIC;
SELECT NOW();
UPDATE ${TABLE_NAME} SET c1 = 1 WHERE id = 1;
SELECT SLEEP(8);
COMMIT;