CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT DEFAULT 1, c2 VARCHAR(11));
ALTER TABLE ${TABLE_NAME} COMMENT 'test create table';
ALTER TABLE ${TABLE_NAME} ALTER COLUMN c1 SET DEFAULT 100;
ALTER TABLE ${TABLE_NAME} MODIFY COLUMN c2 TEXT;
SHOW CREATE TABLE ${TABLE_NAME};
RENAME TABLE ${TABLE_NAME} TO ${TABLE_NAME}_rename;
ALTER TABLE ${TABLE_NAME}_rename ADD COLUMN c3 DATETIME;
SHOW CREATE TABLE ${TABLE_NAME};
ALTER TABLE ${TABLE_NAME}_rename DROP COLUMN c3;
SHOW CREATE TABLE ${TABLE_NAME}_rename;
DROP TABLE ${TABLE_NAME}_rename;


