CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, c1 INT NOT NULL, c2 VARCHAR(11) DEFAULT 'abc');
INSERT INTO ${TABLE_NAME} (id, c1) VALUES (1, 100),(2, 200),(3,300);
ALTER TABLE ${TABLE_NAME} MODIFY COLUMN c1 BIGINT;
ALTER TABLE ${TABLE_NAME} MODIFY c1 VARCHAR(11) NULL;
ALTER TABLE ${TABLE_NAME} MODIFY c2 VARCHAR(11) DEFAULT 'xyz';
SHOW CREATE TABLE ${TABLE_NAME};
INSERT INTO ${TABLE_NAME} (id, c1) VALUES (4, 400),(5, NULL);
SELECT * FROM ${TABLE_NAME};