CREATE TABLE ${TABLE_NAME} (id INT PRIMARY KEY, name VARCHAR(11));
INSERT INTO ${TABLE_NAME} VALUES (1, 'Green'), (2, 'Jim'), (3, 'Lucy');
ANALYZE TABLE ${TABLE_NAME};
EXPLAIN ANALYZE SELECT * FROM ${TABLE_NAME};